apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpcgreeter
  name: grpcgreeter
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpcgreeter
  template:
    metadata:
      labels:
        app: grpcgreeter
    spec:
      containers:
      - image: crystalline407/grpcgreeter:latest
        env:
        - name: "Logging__LogLevel__Microsoft.AspNetCore.Hosting.Diagnostics"
          value: "Information"
        name: grpcgreeter
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpcgreeter
  name: grpcgreeter
  namespace: app
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: grpc
  selector:
    app: grpcgreeter

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
  - hosts:
    - aks210401.japaneast.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: aks210401.japaneast.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: grpcgreeter
          servicePort: grpc
